dist: xenial
language: python
sudo: required
python: "3.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install g++-4.9-arm-linux-gnueabi
install:
  - echo done
script: python -m pytest test
